services:
  app:
    build: .
    container_name: pr-assignment-app
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test:
        ["CMD-SHELL", "wget --spider -q http://localhost:${PORT:-8080}/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  postgres:
    image: postgres:18.1-alpine3.22
    container_name: pr-assignment-db
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./deployments/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  postgres-data:
