// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"

	"github.com/google/uuid"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
)

// GetTeamParams is parameters of GetTeam operation.
type GetTeamParams struct {
	// Уникальное имя команды.
	TeamName TeamName
}

func unpackGetTeamParams(packed middleware.Parameters) (params GetTeamParams) {
	{
		key := middleware.ParameterKey{
			Name: "team_name",
			In:   "query",
		}
		params.TeamName = packed[key].(TeamName)
	}
	return params
}

func decodeGetTeamParams(args [0]string, argsEscaped bool, r *http.Request) (params GetTeamParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: team_name.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "team_name",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotTeamNameVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotTeamNameVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.TeamName = TeamName(paramsDotTeamNameVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := params.TeamName.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "team_name",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// GetUserReviewsParams is parameters of GetUserReviews operation.
type GetUserReviewsParams struct {
	// Идентификатор пользователя.
	UserID uuid.UUID
}

func unpackGetUserReviewsParams(packed middleware.Parameters) (params GetUserReviewsParams) {
	{
		key := middleware.ParameterKey{
			Name: "user_id",
			In:   "query",
		}
		params.UserID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetUserReviewsParams(args [0]string, argsEscaped bool, r *http.Request) (params GetUserReviewsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: user_id.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "user_id",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.UserID = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "user_id",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
