// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CheckHealth implements CheckHealth operation.
//
// Проверка состояния сервиса.
//
// GET /health
func (UnimplementedHandler) CheckHealth(ctx context.Context) (r CheckHealthRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreatePullRequest implements CreatePullRequest operation.
//
// Создать PR и автоматически назначить до 2 ревьюверов
// из команды автора.
//
// POST /pullRequest/create
func (UnimplementedHandler) CreatePullRequest(ctx context.Context, req *CreatePullRequestReq) (r CreatePullRequestRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTeam implements CreateTeam operation.
//
// Создать команду с участниками (создаёт/обновляет
// пользователей).
//
// POST /team/add
func (UnimplementedHandler) CreateTeam(ctx context.Context, req *Team) (r CreateTeamRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeactivateTeamMembers implements DeactivateTeamMembers operation.
//
// Массовая деактивация пользователей команды с
// удалением из открытых PR.
//
// POST /team/deactivate
func (UnimplementedHandler) DeactivateTeamMembers(ctx context.Context, req *DeactivateTeamMembersReq) (r DeactivateTeamMembersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAssignmentStats implements GetAssignmentStats operation.
//
// Получить статистику назначений по пользователям и PR.
//
// GET /stats/assignments
func (UnimplementedHandler) GetAssignmentStats(ctx context.Context) (r GetAssignmentStatsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTeam implements GetTeam operation.
//
// Получить команду с участниками.
//
// GET /team/get
func (UnimplementedHandler) GetTeam(ctx context.Context, params GetTeamParams) (r GetTeamRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserReviews implements GetUserReviews operation.
//
// Получить PR'ы, где пользователь назначен ревьювером.
//
// GET /users/getReview
func (UnimplementedHandler) GetUserReviews(ctx context.Context, params GetUserReviewsParams) (r GetUserReviewsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// MergePullRequest implements MergePullRequest operation.
//
// Пометить PR как MERGED (идемпотентная операция).
//
// POST /pullRequest/merge
func (UnimplementedHandler) MergePullRequest(ctx context.Context, req *MergePullRequestReq) (r MergePullRequestRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReassignReviewer implements ReassignReviewer operation.
//
// Переназначить конкретного ревьювера на другого из
// его команды.
//
// POST /pullRequest/reassign
func (UnimplementedHandler) ReassignReviewer(ctx context.Context, req *ReassignReviewerReq) (r ReassignReviewerRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SetUserActive implements SetUserActive operation.
//
// Установить флаг активности пользователя.
//
// POST /users/setIsActive
func (UnimplementedHandler) SetUserActive(ctx context.Context, req *SetUserActiveReq) (r SetUserActiveRes, _ error) {
	return r, ht.ErrNotImplemented
}
