// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CheckHealthOperation           OperationName = "CheckHealth"
	CreatePullRequestOperation     OperationName = "CreatePullRequest"
	CreateTeamOperation            OperationName = "CreateTeam"
	DeactivateTeamMembersOperation OperationName = "DeactivateTeamMembers"
	GetAssignmentStatsOperation    OperationName = "GetAssignmentStats"
	GetTeamOperation               OperationName = "GetTeam"
	GetUserReviewsOperation        OperationName = "GetUserReviews"
	MergePullRequestOperation      OperationName = "MergePullRequest"
	ReassignReviewerOperation      OperationName = "ReassignReviewer"
	SetUserActiveOperation         OperationName = "SetUserActive"
)
