// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CheckHealth implements CheckHealth operation.
	//
	// Проверка состояния сервиса.
	//
	// GET /health
	CheckHealth(ctx context.Context) (CheckHealthRes, error)
	// CreatePullRequest implements CreatePullRequest operation.
	//
	// Создать PR и автоматически назначить до 2 ревьюверов
	// из команды автора.
	//
	// POST /pullRequest/create
	CreatePullRequest(ctx context.Context, req *CreatePullRequestReq) (CreatePullRequestRes, error)
	// CreateTeam implements CreateTeam operation.
	//
	// Создать команду с участниками (создаёт/обновляет
	// пользователей).
	//
	// POST /team/add
	CreateTeam(ctx context.Context, req *Team) (CreateTeamRes, error)
	// DeactivateTeamMembers implements DeactivateTeamMembers operation.
	//
	// Массовая деактивация пользователей команды с
	// удалением из открытых PR.
	//
	// POST /team/deactivate
	DeactivateTeamMembers(ctx context.Context, req *DeactivateTeamMembersReq) (DeactivateTeamMembersRes, error)
	// GetAssignmentStats implements GetAssignmentStats operation.
	//
	// Получить статистику назначений по пользователям и PR.
	//
	// GET /stats/assignments
	GetAssignmentStats(ctx context.Context) (GetAssignmentStatsRes, error)
	// GetTeam implements GetTeam operation.
	//
	// Получить команду с участниками.
	//
	// GET /team/get
	GetTeam(ctx context.Context, params GetTeamParams) (GetTeamRes, error)
	// GetUserReviews implements GetUserReviews operation.
	//
	// Получить PR'ы, где пользователь назначен ревьювером.
	//
	// GET /users/getReview
	GetUserReviews(ctx context.Context, params GetUserReviewsParams) (GetUserReviewsRes, error)
	// MergePullRequest implements MergePullRequest operation.
	//
	// Пометить PR как MERGED (идемпотентная операция).
	//
	// POST /pullRequest/merge
	MergePullRequest(ctx context.Context, req *MergePullRequestReq) (MergePullRequestRes, error)
	// ReassignReviewer implements ReassignReviewer operation.
	//
	// Переназначить конкретного ревьювера на другого из
	// его команды.
	//
	// POST /pullRequest/reassign
	ReassignReviewer(ctx context.Context, req *ReassignReviewerReq) (ReassignReviewerRes, error)
	// SetUserActive implements SetUserActive operation.
	//
	// Установить флаг активности пользователя.
	//
	// POST /users/setIsActive
	SetUserActive(ctx context.Context, req *SetUserActiveReq) (SetUserActiveRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
