// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/url"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/uri"
)

func trimTrailingSlashes(u *url.URL) {
	u.Path = strings.TrimRight(u.Path, "/")
	u.RawPath = strings.TrimRight(u.RawPath, "/")
}

// Invoker invokes operations described by OpenAPI v3 specification.
type Invoker interface {
	// CheckHealth invokes CheckHealth operation.
	//
	// Проверка состояния сервиса.
	//
	// GET /health
	CheckHealth(ctx context.Context) (CheckHealthRes, error)
	// CreatePullRequest invokes CreatePullRequest operation.
	//
	// Создать PR и автоматически назначить до 2 ревьюверов
	// из команды автора.
	//
	// POST /pullRequest/create
	CreatePullRequest(ctx context.Context, request *CreatePullRequestReq) (CreatePullRequestRes, error)
	// CreateTeam invokes CreateTeam operation.
	//
	// Создать команду с участниками (создаёт/обновляет
	// пользователей).
	//
	// POST /team/add
	CreateTeam(ctx context.Context, request *Team) (CreateTeamRes, error)
	// DeactivateTeamMembers invokes DeactivateTeamMembers operation.
	//
	// Массовая деактивация пользователей команды с
	// удалением из открытых PR.
	//
	// POST /team/deactivate
	DeactivateTeamMembers(ctx context.Context, request *DeactivateTeamMembersReq) (DeactivateTeamMembersRes, error)
	// GetAssignmentStats invokes GetAssignmentStats operation.
	//
	// Получить статистику назначений по пользователям и PR.
	//
	// GET /stats/assignments
	GetAssignmentStats(ctx context.Context) (GetAssignmentStatsRes, error)
	// GetTeam invokes GetTeam operation.
	//
	// Получить команду с участниками.
	//
	// GET /team/get
	GetTeam(ctx context.Context, params GetTeamParams) (GetTeamRes, error)
	// GetUserReviews invokes GetUserReviews operation.
	//
	// Получить PR'ы, где пользователь назначен ревьювером.
	//
	// GET /users/getReview
	GetUserReviews(ctx context.Context, params GetUserReviewsParams) (GetUserReviewsRes, error)
	// MergePullRequest invokes MergePullRequest operation.
	//
	// Пометить PR как MERGED (идемпотентная операция).
	//
	// POST /pullRequest/merge
	MergePullRequest(ctx context.Context, request *MergePullRequestReq) (MergePullRequestRes, error)
	// ReassignReviewer invokes ReassignReviewer operation.
	//
	// Переназначить конкретного ревьювера на другого из
	// его команды.
	//
	// POST /pullRequest/reassign
	ReassignReviewer(ctx context.Context, request *ReassignReviewerReq) (ReassignReviewerRes, error)
	// SetUserActive invokes SetUserActive operation.
	//
	// Установить флаг активности пользователя.
	//
	// POST /users/setIsActive
	SetUserActive(ctx context.Context, request *SetUserActiveReq) (SetUserActiveRes, error)
}

// Client implements OAS client.
type Client struct {
	serverURL *url.URL
	baseClient
}

var _ Handler = struct {
	*Client
}{}

// NewClient initializes new Client defined by OAS.
func NewClient(serverURL string, opts ...ClientOption) (*Client, error) {
	u, err := url.Parse(serverURL)
	if err != nil {
		return nil, err
	}
	trimTrailingSlashes(u)

	c, err := newClientConfig(opts...).baseClient()
	if err != nil {
		return nil, err
	}
	return &Client{
		serverURL:  u,
		baseClient: c,
	}, nil
}

type serverURLKey struct{}

// WithServerURL sets context key to override server URL.
func WithServerURL(ctx context.Context, u *url.URL) context.Context {
	return context.WithValue(ctx, serverURLKey{}, u)
}

func (c *Client) requestURL(ctx context.Context) *url.URL {
	u, ok := ctx.Value(serverURLKey{}).(*url.URL)
	if !ok {
		return c.serverURL
	}
	return u
}

// CheckHealth invokes CheckHealth operation.
//
// Проверка состояния сервиса.
//
// GET /health
func (c *Client) CheckHealth(ctx context.Context) (CheckHealthRes, error) {
	res, err := c.sendCheckHealth(ctx)
	return res, err
}

func (c *Client) sendCheckHealth(ctx context.Context) (res CheckHealthRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/health"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeCheckHealthResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CreatePullRequest invokes CreatePullRequest operation.
//
// Создать PR и автоматически назначить до 2 ревьюверов
// из команды автора.
//
// POST /pullRequest/create
func (c *Client) CreatePullRequest(ctx context.Context, request *CreatePullRequestReq) (CreatePullRequestRes, error) {
	res, err := c.sendCreatePullRequest(ctx, request)
	return res, err
}

func (c *Client) sendCreatePullRequest(ctx context.Context, request *CreatePullRequestReq) (res CreatePullRequestRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/pullRequest/create"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeCreatePullRequestRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeCreatePullRequestResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CreateTeam invokes CreateTeam operation.
//
// Создать команду с участниками (создаёт/обновляет
// пользователей).
//
// POST /team/add
func (c *Client) CreateTeam(ctx context.Context, request *Team) (CreateTeamRes, error) {
	res, err := c.sendCreateTeam(ctx, request)
	return res, err
}

func (c *Client) sendCreateTeam(ctx context.Context, request *Team) (res CreateTeamRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/team/add"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeCreateTeamRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeCreateTeamResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// DeactivateTeamMembers invokes DeactivateTeamMembers operation.
//
// Массовая деактивация пользователей команды с
// удалением из открытых PR.
//
// POST /team/deactivate
func (c *Client) DeactivateTeamMembers(ctx context.Context, request *DeactivateTeamMembersReq) (DeactivateTeamMembersRes, error) {
	res, err := c.sendDeactivateTeamMembers(ctx, request)
	return res, err
}

func (c *Client) sendDeactivateTeamMembers(ctx context.Context, request *DeactivateTeamMembersReq) (res DeactivateTeamMembersRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/team/deactivate"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeDeactivateTeamMembersRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeDeactivateTeamMembersResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetAssignmentStats invokes GetAssignmentStats operation.
//
// Получить статистику назначений по пользователям и PR.
//
// GET /stats/assignments
func (c *Client) GetAssignmentStats(ctx context.Context) (GetAssignmentStatsRes, error) {
	res, err := c.sendGetAssignmentStats(ctx)
	return res, err
}

func (c *Client) sendGetAssignmentStats(ctx context.Context) (res GetAssignmentStatsRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/stats/assignments"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeGetAssignmentStatsResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetTeam invokes GetTeam operation.
//
// Получить команду с участниками.
//
// GET /team/get
func (c *Client) GetTeam(ctx context.Context, params GetTeamParams) (GetTeamRes, error) {
	res, err := c.sendGetTeam(ctx, params)
	return res, err
}

func (c *Client) sendGetTeam(ctx context.Context, params GetTeamParams) (res GetTeamRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/team/get"
	uri.AddPathParts(u, pathParts[:]...)

	q := uri.NewQueryEncoder()
	{
		// Encode "team_name" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "team_name",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			return e.EncodeValue(conv.StringToString(params.TeamName))
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeGetTeamResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetUserReviews invokes GetUserReviews operation.
//
// Получить PR'ы, где пользователь назначен ревьювером.
//
// GET /users/getReview
func (c *Client) GetUserReviews(ctx context.Context, params GetUserReviewsParams) (GetUserReviewsRes, error) {
	res, err := c.sendGetUserReviews(ctx, params)
	return res, err
}

func (c *Client) sendGetUserReviews(ctx context.Context, params GetUserReviewsParams) (res GetUserReviewsRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/users/getReview"
	uri.AddPathParts(u, pathParts[:]...)

	q := uri.NewQueryEncoder()
	{
		// Encode "user_id" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "user_id",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			return e.EncodeValue(conv.UUIDToString(params.UserID))
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeGetUserReviewsResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// MergePullRequest invokes MergePullRequest operation.
//
// Пометить PR как MERGED (идемпотентная операция).
//
// POST /pullRequest/merge
func (c *Client) MergePullRequest(ctx context.Context, request *MergePullRequestReq) (MergePullRequestRes, error) {
	res, err := c.sendMergePullRequest(ctx, request)
	return res, err
}

func (c *Client) sendMergePullRequest(ctx context.Context, request *MergePullRequestReq) (res MergePullRequestRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/pullRequest/merge"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeMergePullRequestRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeMergePullRequestResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ReassignReviewer invokes ReassignReviewer operation.
//
// Переназначить конкретного ревьювера на другого из
// его команды.
//
// POST /pullRequest/reassign
func (c *Client) ReassignReviewer(ctx context.Context, request *ReassignReviewerReq) (ReassignReviewerRes, error) {
	res, err := c.sendReassignReviewer(ctx, request)
	return res, err
}

func (c *Client) sendReassignReviewer(ctx context.Context, request *ReassignReviewerReq) (res ReassignReviewerRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/pullRequest/reassign"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeReassignReviewerRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeReassignReviewerResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SetUserActive invokes SetUserActive operation.
//
// Установить флаг активности пользователя.
//
// POST /users/setIsActive
func (c *Client) SetUserActive(ctx context.Context, request *SetUserActiveReq) (SetUserActiveRes, error) {
	res, err := c.sendSetUserActive(ctx, request)
	return res, err
}

func (c *Client) sendSetUserActive(ctx context.Context, request *SetUserActiveReq) (res SetUserActiveRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/users/setIsActive"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeSetUserActiveRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeSetUserActiveResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}
