// Code generated by ogen, DO NOT EDIT.
package api

type CheckHealthRes interface {
	checkHealthRes()
}

type CreatePullRequestRes interface {
	createPullRequestRes()
}

type CreateTeamRes interface {
	createTeamRes()
}

type DeactivateTeamMembersRes interface {
	deactivateTeamMembersRes()
}

type GetAssignmentStatsRes interface {
	getAssignmentStatsRes()
}

type GetTeamRes interface {
	getTeamRes()
}

type GetUserReviewsRes interface {
	getUserReviewsRes()
}

type MergePullRequestRes interface {
	mergePullRequestRes()
}

type ReassignReviewerRes interface {
	reassignReviewerRes()
}

type SetUserActiveRes interface {
	setUserActiveRes()
}
