// Code generated by ogen, DO NOT EDIT.

package api

import (
	"io"
	"time"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

type CheckHealthOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s CheckHealthOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*CheckHealthOK) checkHealthRes() {}

type CreatePullRequestBadRequest ErrorResponse

func (*CreatePullRequestBadRequest) createPullRequestRes() {}

type CreatePullRequestConflict ErrorResponse

func (*CreatePullRequestConflict) createPullRequestRes() {}

type CreatePullRequestCreated struct {
	Pr OptPullRequest `json:"pr"`
}

// GetPr returns the value of Pr.
func (s *CreatePullRequestCreated) GetPr() OptPullRequest {
	return s.Pr
}

// SetPr sets the value of Pr.
func (s *CreatePullRequestCreated) SetPr(val OptPullRequest) {
	s.Pr = val
}

func (*CreatePullRequestCreated) createPullRequestRes() {}

type CreatePullRequestInternalServerError ErrorResponse

func (*CreatePullRequestInternalServerError) createPullRequestRes() {}

type CreatePullRequestNotFound ErrorResponse

func (*CreatePullRequestNotFound) createPullRequestRes() {}

type CreatePullRequestReq struct {
	PullRequestID   uuid.UUID `json:"pull_request_id"`
	PullRequestName string    `json:"pull_request_name"`
	AuthorID        uuid.UUID `json:"author_id"`
}

// GetPullRequestID returns the value of PullRequestID.
func (s *CreatePullRequestReq) GetPullRequestID() uuid.UUID {
	return s.PullRequestID
}

// GetPullRequestName returns the value of PullRequestName.
func (s *CreatePullRequestReq) GetPullRequestName() string {
	return s.PullRequestName
}

// GetAuthorID returns the value of AuthorID.
func (s *CreatePullRequestReq) GetAuthorID() uuid.UUID {
	return s.AuthorID
}

// SetPullRequestID sets the value of PullRequestID.
func (s *CreatePullRequestReq) SetPullRequestID(val uuid.UUID) {
	s.PullRequestID = val
}

// SetPullRequestName sets the value of PullRequestName.
func (s *CreatePullRequestReq) SetPullRequestName(val string) {
	s.PullRequestName = val
}

// SetAuthorID sets the value of AuthorID.
func (s *CreatePullRequestReq) SetAuthorID(val uuid.UUID) {
	s.AuthorID = val
}

type CreateTeamBadRequest ErrorResponse

func (*CreateTeamBadRequest) createTeamRes() {}

type CreateTeamConflict ErrorResponse

func (*CreateTeamConflict) createTeamRes() {}

type CreateTeamCreated struct {
	Team OptTeam `json:"team"`
}

// GetTeam returns the value of Team.
func (s *CreateTeamCreated) GetTeam() OptTeam {
	return s.Team
}

// SetTeam sets the value of Team.
func (s *CreateTeamCreated) SetTeam(val OptTeam) {
	s.Team = val
}

func (*CreateTeamCreated) createTeamRes() {}

type CreateTeamInternalServerError ErrorResponse

func (*CreateTeamInternalServerError) createTeamRes() {}

type DeactivateTeamMembersBadRequest ErrorResponse

func (*DeactivateTeamMembersBadRequest) deactivateTeamMembersRes() {}

type DeactivateTeamMembersInternalServerError ErrorResponse

func (*DeactivateTeamMembersInternalServerError) deactivateTeamMembersRes() {}

type DeactivateTeamMembersNotFound ErrorResponse

func (*DeactivateTeamMembersNotFound) deactivateTeamMembersRes() {}

type DeactivateTeamMembersOK struct {
	// Количество деактивированных пользователей.
	DeactivatedCount int `json:"deactivated_count"`
	// Количество удаленных ревьюверов из открытых PR.
	RemovedCount int `json:"removed_count"`
}

// GetDeactivatedCount returns the value of DeactivatedCount.
func (s *DeactivateTeamMembersOK) GetDeactivatedCount() int {
	return s.DeactivatedCount
}

// GetRemovedCount returns the value of RemovedCount.
func (s *DeactivateTeamMembersOK) GetRemovedCount() int {
	return s.RemovedCount
}

// SetDeactivatedCount sets the value of DeactivatedCount.
func (s *DeactivateTeamMembersOK) SetDeactivatedCount(val int) {
	s.DeactivatedCount = val
}

// SetRemovedCount sets the value of RemovedCount.
func (s *DeactivateTeamMembersOK) SetRemovedCount(val int) {
	s.RemovedCount = val
}

func (*DeactivateTeamMembersOK) deactivateTeamMembersRes() {}

type DeactivateTeamMembersReq struct {
	TeamName string `json:"team_name"`
}

// GetTeamName returns the value of TeamName.
func (s *DeactivateTeamMembersReq) GetTeamName() string {
	return s.TeamName
}

// SetTeamName sets the value of TeamName.
func (s *DeactivateTeamMembersReq) SetTeamName(val string) {
	s.TeamName = val
}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Error ErrorResponseError `json:"error"`
}

// GetError returns the value of Error.
func (s *ErrorResponse) GetError() ErrorResponseError {
	return s.Error
}

// SetError sets the value of Error.
func (s *ErrorResponse) SetError(val ErrorResponseError) {
	s.Error = val
}

func (*ErrorResponse) checkHealthRes()        {}
func (*ErrorResponse) getAssignmentStatsRes() {}

type ErrorResponseError struct {
	Code    ErrorResponseErrorCode `json:"code"`
	Message string                 `json:"message"`
}

// GetCode returns the value of Code.
func (s *ErrorResponseError) GetCode() ErrorResponseErrorCode {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ErrorResponseError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ErrorResponseError) SetCode(val ErrorResponseErrorCode) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ErrorResponseError) SetMessage(val string) {
	s.Message = val
}

type ErrorResponseErrorCode string

const (
	ErrorResponseErrorCodeTEAMEXISTS    ErrorResponseErrorCode = "TEAM_EXISTS"
	ErrorResponseErrorCodePREXISTS      ErrorResponseErrorCode = "PR_EXISTS"
	ErrorResponseErrorCodePRMERGED      ErrorResponseErrorCode = "PR_MERGED"
	ErrorResponseErrorCodeNOTASSIGNED   ErrorResponseErrorCode = "NOT_ASSIGNED"
	ErrorResponseErrorCodeNOCANDIDATE   ErrorResponseErrorCode = "NO_CANDIDATE"
	ErrorResponseErrorCodeNOTFOUND      ErrorResponseErrorCode = "NOT_FOUND"
	ErrorResponseErrorCodeINVALIDINPUT  ErrorResponseErrorCode = "INVALID_INPUT"
	ErrorResponseErrorCodeINTERNALERROR ErrorResponseErrorCode = "INTERNAL_ERROR"
)

// AllValues returns all ErrorResponseErrorCode values.
func (ErrorResponseErrorCode) AllValues() []ErrorResponseErrorCode {
	return []ErrorResponseErrorCode{
		ErrorResponseErrorCodeTEAMEXISTS,
		ErrorResponseErrorCodePREXISTS,
		ErrorResponseErrorCodePRMERGED,
		ErrorResponseErrorCodeNOTASSIGNED,
		ErrorResponseErrorCodeNOCANDIDATE,
		ErrorResponseErrorCodeNOTFOUND,
		ErrorResponseErrorCodeINVALIDINPUT,
		ErrorResponseErrorCodeINTERNALERROR,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ErrorResponseErrorCode) MarshalText() ([]byte, error) {
	switch s {
	case ErrorResponseErrorCodeTEAMEXISTS:
		return []byte(s), nil
	case ErrorResponseErrorCodePREXISTS:
		return []byte(s), nil
	case ErrorResponseErrorCodePRMERGED:
		return []byte(s), nil
	case ErrorResponseErrorCodeNOTASSIGNED:
		return []byte(s), nil
	case ErrorResponseErrorCodeNOCANDIDATE:
		return []byte(s), nil
	case ErrorResponseErrorCodeNOTFOUND:
		return []byte(s), nil
	case ErrorResponseErrorCodeINVALIDINPUT:
		return []byte(s), nil
	case ErrorResponseErrorCodeINTERNALERROR:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ErrorResponseErrorCode) UnmarshalText(data []byte) error {
	switch ErrorResponseErrorCode(data) {
	case ErrorResponseErrorCodeTEAMEXISTS:
		*s = ErrorResponseErrorCodeTEAMEXISTS
		return nil
	case ErrorResponseErrorCodePREXISTS:
		*s = ErrorResponseErrorCodePREXISTS
		return nil
	case ErrorResponseErrorCodePRMERGED:
		*s = ErrorResponseErrorCodePRMERGED
		return nil
	case ErrorResponseErrorCodeNOTASSIGNED:
		*s = ErrorResponseErrorCodeNOTASSIGNED
		return nil
	case ErrorResponseErrorCodeNOCANDIDATE:
		*s = ErrorResponseErrorCodeNOCANDIDATE
		return nil
	case ErrorResponseErrorCodeNOTFOUND:
		*s = ErrorResponseErrorCodeNOTFOUND
		return nil
	case ErrorResponseErrorCodeINVALIDINPUT:
		*s = ErrorResponseErrorCodeINVALIDINPUT
		return nil
	case ErrorResponseErrorCodeINTERNALERROR:
		*s = ErrorResponseErrorCodeINTERNALERROR
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type GetAssignmentStatsOK struct {
	UserStats []GetAssignmentStatsOKUserStatsItem `json:"user_stats"`
	PrStats   []GetAssignmentStatsOKPrStatsItem   `json:"pr_stats"`
}

// GetUserStats returns the value of UserStats.
func (s *GetAssignmentStatsOK) GetUserStats() []GetAssignmentStatsOKUserStatsItem {
	return s.UserStats
}

// GetPrStats returns the value of PrStats.
func (s *GetAssignmentStatsOK) GetPrStats() []GetAssignmentStatsOKPrStatsItem {
	return s.PrStats
}

// SetUserStats sets the value of UserStats.
func (s *GetAssignmentStatsOK) SetUserStats(val []GetAssignmentStatsOKUserStatsItem) {
	s.UserStats = val
}

// SetPrStats sets the value of PrStats.
func (s *GetAssignmentStatsOK) SetPrStats(val []GetAssignmentStatsOKPrStatsItem) {
	s.PrStats = val
}

func (*GetAssignmentStatsOK) getAssignmentStatsRes() {}

type GetAssignmentStatsOKPrStatsItem struct {
	PullRequestID   uuid.UUID `json:"pull_request_id"`
	PullRequestName string    `json:"pull_request_name"`
	ReviewerCount   int       `json:"reviewer_count"`
}

// GetPullRequestID returns the value of PullRequestID.
func (s *GetAssignmentStatsOKPrStatsItem) GetPullRequestID() uuid.UUID {
	return s.PullRequestID
}

// GetPullRequestName returns the value of PullRequestName.
func (s *GetAssignmentStatsOKPrStatsItem) GetPullRequestName() string {
	return s.PullRequestName
}

// GetReviewerCount returns the value of ReviewerCount.
func (s *GetAssignmentStatsOKPrStatsItem) GetReviewerCount() int {
	return s.ReviewerCount
}

// SetPullRequestID sets the value of PullRequestID.
func (s *GetAssignmentStatsOKPrStatsItem) SetPullRequestID(val uuid.UUID) {
	s.PullRequestID = val
}

// SetPullRequestName sets the value of PullRequestName.
func (s *GetAssignmentStatsOKPrStatsItem) SetPullRequestName(val string) {
	s.PullRequestName = val
}

// SetReviewerCount sets the value of ReviewerCount.
func (s *GetAssignmentStatsOKPrStatsItem) SetReviewerCount(val int) {
	s.ReviewerCount = val
}

type GetAssignmentStatsOKUserStatsItem struct {
	UserID          uuid.UUID `json:"user_id"`
	Username        string    `json:"username"`
	AssignmentCount int       `json:"assignment_count"`
}

// GetUserID returns the value of UserID.
func (s *GetAssignmentStatsOKUserStatsItem) GetUserID() uuid.UUID {
	return s.UserID
}

// GetUsername returns the value of Username.
func (s *GetAssignmentStatsOKUserStatsItem) GetUsername() string {
	return s.Username
}

// GetAssignmentCount returns the value of AssignmentCount.
func (s *GetAssignmentStatsOKUserStatsItem) GetAssignmentCount() int {
	return s.AssignmentCount
}

// SetUserID sets the value of UserID.
func (s *GetAssignmentStatsOKUserStatsItem) SetUserID(val uuid.UUID) {
	s.UserID = val
}

// SetUsername sets the value of Username.
func (s *GetAssignmentStatsOKUserStatsItem) SetUsername(val string) {
	s.Username = val
}

// SetAssignmentCount sets the value of AssignmentCount.
func (s *GetAssignmentStatsOKUserStatsItem) SetAssignmentCount(val int) {
	s.AssignmentCount = val
}

type GetTeamBadRequest ErrorResponse

func (*GetTeamBadRequest) getTeamRes() {}

type GetTeamInternalServerError ErrorResponse

func (*GetTeamInternalServerError) getTeamRes() {}

type GetTeamNotFound ErrorResponse

func (*GetTeamNotFound) getTeamRes() {}

type GetUserReviewsBadRequest ErrorResponse

func (*GetUserReviewsBadRequest) getUserReviewsRes() {}

type GetUserReviewsInternalServerError ErrorResponse

func (*GetUserReviewsInternalServerError) getUserReviewsRes() {}

type GetUserReviewsNotFound ErrorResponse

func (*GetUserReviewsNotFound) getUserReviewsRes() {}

type GetUserReviewsOK struct {
	UserID       uuid.UUID          `json:"user_id"`
	PullRequests []PullRequestShort `json:"pull_requests"`
}

// GetUserID returns the value of UserID.
func (s *GetUserReviewsOK) GetUserID() uuid.UUID {
	return s.UserID
}

// GetPullRequests returns the value of PullRequests.
func (s *GetUserReviewsOK) GetPullRequests() []PullRequestShort {
	return s.PullRequests
}

// SetUserID sets the value of UserID.
func (s *GetUserReviewsOK) SetUserID(val uuid.UUID) {
	s.UserID = val
}

// SetPullRequests sets the value of PullRequests.
func (s *GetUserReviewsOK) SetPullRequests(val []PullRequestShort) {
	s.PullRequests = val
}

func (*GetUserReviewsOK) getUserReviewsRes() {}

type MergePullRequestBadRequest ErrorResponse

func (*MergePullRequestBadRequest) mergePullRequestRes() {}

type MergePullRequestInternalServerError ErrorResponse

func (*MergePullRequestInternalServerError) mergePullRequestRes() {}

type MergePullRequestNotFound ErrorResponse

func (*MergePullRequestNotFound) mergePullRequestRes() {}

type MergePullRequestOK struct {
	Pr OptPullRequest `json:"pr"`
}

// GetPr returns the value of Pr.
func (s *MergePullRequestOK) GetPr() OptPullRequest {
	return s.Pr
}

// SetPr sets the value of Pr.
func (s *MergePullRequestOK) SetPr(val OptPullRequest) {
	s.Pr = val
}

func (*MergePullRequestOK) mergePullRequestRes() {}

type MergePullRequestReq struct {
	PullRequestID uuid.UUID `json:"pull_request_id"`
}

// GetPullRequestID returns the value of PullRequestID.
func (s *MergePullRequestReq) GetPullRequestID() uuid.UUID {
	return s.PullRequestID
}

// SetPullRequestID sets the value of PullRequestID.
func (s *MergePullRequestReq) SetPullRequestID(val uuid.UUID) {
	s.PullRequestID = val
}

// NewOptNilDateTime returns new OptNilDateTime with value set to v.
func NewOptNilDateTime(v time.Time) OptNilDateTime {
	return OptNilDateTime{
		Value: v,
		Set:   true,
	}
}

// OptNilDateTime is optional nullable time.Time.
type OptNilDateTime struct {
	Value time.Time
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilDateTime was set.
func (o OptNilDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilDateTime) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilDateTime) SetToNull() {
	o.Set = true
	o.Null = true
	var v time.Time
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilDateTime) Get() (v time.Time, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPullRequest returns new OptPullRequest with value set to v.
func NewOptPullRequest(v PullRequest) OptPullRequest {
	return OptPullRequest{
		Value: v,
		Set:   true,
	}
}

// OptPullRequest is optional PullRequest.
type OptPullRequest struct {
	Value PullRequest
	Set   bool
}

// IsSet returns true if OptPullRequest was set.
func (o OptPullRequest) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPullRequest) Reset() {
	var v PullRequest
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPullRequest) SetTo(v PullRequest) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPullRequest) Get() (v PullRequest, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPullRequest) Or(d PullRequest) PullRequest {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptTeam returns new OptTeam with value set to v.
func NewOptTeam(v Team) OptTeam {
	return OptTeam{
		Value: v,
		Set:   true,
	}
}

// OptTeam is optional Team.
type OptTeam struct {
	Value Team
	Set   bool
}

// IsSet returns true if OptTeam was set.
func (o OptTeam) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptTeam) Reset() {
	var v Team
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptTeam) SetTo(v Team) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptTeam) Get() (v Team, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptTeam) Or(d Team) Team {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUser returns new OptUser with value set to v.
func NewOptUser(v User) OptUser {
	return OptUser{
		Value: v,
		Set:   true,
	}
}

// OptUser is optional User.
type OptUser struct {
	Value User
	Set   bool
}

// IsSet returns true if OptUser was set.
func (o OptUser) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUser) Reset() {
	var v User
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUser) SetTo(v User) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUser) Get() (v User, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUser) Or(d User) User {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/PullRequest
type PullRequest struct {
	PullRequestID   uuid.UUID         `json:"pull_request_id"`
	PullRequestName string            `json:"pull_request_name"`
	AuthorID        uuid.UUID         `json:"author_id"`
	Status          PullRequestStatus `json:"status"`
	// User_id назначенных ревьюверов (0..2).
	AssignedReviewers []uuid.UUID    `json:"assigned_reviewers"`
	CreatedAt         OptNilDateTime `json:"createdAt"`
	MergedAt          OptNilDateTime `json:"mergedAt"`
}

// GetPullRequestID returns the value of PullRequestID.
func (s *PullRequest) GetPullRequestID() uuid.UUID {
	return s.PullRequestID
}

// GetPullRequestName returns the value of PullRequestName.
func (s *PullRequest) GetPullRequestName() string {
	return s.PullRequestName
}

// GetAuthorID returns the value of AuthorID.
func (s *PullRequest) GetAuthorID() uuid.UUID {
	return s.AuthorID
}

// GetStatus returns the value of Status.
func (s *PullRequest) GetStatus() PullRequestStatus {
	return s.Status
}

// GetAssignedReviewers returns the value of AssignedReviewers.
func (s *PullRequest) GetAssignedReviewers() []uuid.UUID {
	return s.AssignedReviewers
}

// GetCreatedAt returns the value of CreatedAt.
func (s *PullRequest) GetCreatedAt() OptNilDateTime {
	return s.CreatedAt
}

// GetMergedAt returns the value of MergedAt.
func (s *PullRequest) GetMergedAt() OptNilDateTime {
	return s.MergedAt
}

// SetPullRequestID sets the value of PullRequestID.
func (s *PullRequest) SetPullRequestID(val uuid.UUID) {
	s.PullRequestID = val
}

// SetPullRequestName sets the value of PullRequestName.
func (s *PullRequest) SetPullRequestName(val string) {
	s.PullRequestName = val
}

// SetAuthorID sets the value of AuthorID.
func (s *PullRequest) SetAuthorID(val uuid.UUID) {
	s.AuthorID = val
}

// SetStatus sets the value of Status.
func (s *PullRequest) SetStatus(val PullRequestStatus) {
	s.Status = val
}

// SetAssignedReviewers sets the value of AssignedReviewers.
func (s *PullRequest) SetAssignedReviewers(val []uuid.UUID) {
	s.AssignedReviewers = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *PullRequest) SetCreatedAt(val OptNilDateTime) {
	s.CreatedAt = val
}

// SetMergedAt sets the value of MergedAt.
func (s *PullRequest) SetMergedAt(val OptNilDateTime) {
	s.MergedAt = val
}

// Ref: #/components/schemas/PullRequestShort
type PullRequestShort struct {
	PullRequestID   uuid.UUID              `json:"pull_request_id"`
	PullRequestName string                 `json:"pull_request_name"`
	AuthorID        uuid.UUID              `json:"author_id"`
	Status          PullRequestShortStatus `json:"status"`
}

// GetPullRequestID returns the value of PullRequestID.
func (s *PullRequestShort) GetPullRequestID() uuid.UUID {
	return s.PullRequestID
}

// GetPullRequestName returns the value of PullRequestName.
func (s *PullRequestShort) GetPullRequestName() string {
	return s.PullRequestName
}

// GetAuthorID returns the value of AuthorID.
func (s *PullRequestShort) GetAuthorID() uuid.UUID {
	return s.AuthorID
}

// GetStatus returns the value of Status.
func (s *PullRequestShort) GetStatus() PullRequestShortStatus {
	return s.Status
}

// SetPullRequestID sets the value of PullRequestID.
func (s *PullRequestShort) SetPullRequestID(val uuid.UUID) {
	s.PullRequestID = val
}

// SetPullRequestName sets the value of PullRequestName.
func (s *PullRequestShort) SetPullRequestName(val string) {
	s.PullRequestName = val
}

// SetAuthorID sets the value of AuthorID.
func (s *PullRequestShort) SetAuthorID(val uuid.UUID) {
	s.AuthorID = val
}

// SetStatus sets the value of Status.
func (s *PullRequestShort) SetStatus(val PullRequestShortStatus) {
	s.Status = val
}

type PullRequestShortStatus string

const (
	PullRequestShortStatusOPEN   PullRequestShortStatus = "OPEN"
	PullRequestShortStatusMERGED PullRequestShortStatus = "MERGED"
)

// AllValues returns all PullRequestShortStatus values.
func (PullRequestShortStatus) AllValues() []PullRequestShortStatus {
	return []PullRequestShortStatus{
		PullRequestShortStatusOPEN,
		PullRequestShortStatusMERGED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PullRequestShortStatus) MarshalText() ([]byte, error) {
	switch s {
	case PullRequestShortStatusOPEN:
		return []byte(s), nil
	case PullRequestShortStatusMERGED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PullRequestShortStatus) UnmarshalText(data []byte) error {
	switch PullRequestShortStatus(data) {
	case PullRequestShortStatusOPEN:
		*s = PullRequestShortStatusOPEN
		return nil
	case PullRequestShortStatusMERGED:
		*s = PullRequestShortStatusMERGED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type PullRequestStatus string

const (
	PullRequestStatusOPEN   PullRequestStatus = "OPEN"
	PullRequestStatusMERGED PullRequestStatus = "MERGED"
)

// AllValues returns all PullRequestStatus values.
func (PullRequestStatus) AllValues() []PullRequestStatus {
	return []PullRequestStatus{
		PullRequestStatusOPEN,
		PullRequestStatusMERGED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PullRequestStatus) MarshalText() ([]byte, error) {
	switch s {
	case PullRequestStatusOPEN:
		return []byte(s), nil
	case PullRequestStatusMERGED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PullRequestStatus) UnmarshalText(data []byte) error {
	switch PullRequestStatus(data) {
	case PullRequestStatusOPEN:
		*s = PullRequestStatusOPEN
		return nil
	case PullRequestStatusMERGED:
		*s = PullRequestStatusMERGED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type ReassignReviewerBadRequest ErrorResponse

func (*ReassignReviewerBadRequest) reassignReviewerRes() {}

type ReassignReviewerConflict ErrorResponse

func (*ReassignReviewerConflict) reassignReviewerRes() {}

type ReassignReviewerInternalServerError ErrorResponse

func (*ReassignReviewerInternalServerError) reassignReviewerRes() {}

type ReassignReviewerNotFound ErrorResponse

func (*ReassignReviewerNotFound) reassignReviewerRes() {}

type ReassignReviewerOK struct {
	Pr PullRequest `json:"pr"`
	// User_id нового ревьювера.
	ReplacedBy uuid.UUID `json:"replaced_by"`
}

// GetPr returns the value of Pr.
func (s *ReassignReviewerOK) GetPr() PullRequest {
	return s.Pr
}

// GetReplacedBy returns the value of ReplacedBy.
func (s *ReassignReviewerOK) GetReplacedBy() uuid.UUID {
	return s.ReplacedBy
}

// SetPr sets the value of Pr.
func (s *ReassignReviewerOK) SetPr(val PullRequest) {
	s.Pr = val
}

// SetReplacedBy sets the value of ReplacedBy.
func (s *ReassignReviewerOK) SetReplacedBy(val uuid.UUID) {
	s.ReplacedBy = val
}

func (*ReassignReviewerOK) reassignReviewerRes() {}

type ReassignReviewerReq struct {
	PullRequestID uuid.UUID `json:"pull_request_id"`
	OldUserID     uuid.UUID `json:"old_user_id"`
}

// GetPullRequestID returns the value of PullRequestID.
func (s *ReassignReviewerReq) GetPullRequestID() uuid.UUID {
	return s.PullRequestID
}

// GetOldUserID returns the value of OldUserID.
func (s *ReassignReviewerReq) GetOldUserID() uuid.UUID {
	return s.OldUserID
}

// SetPullRequestID sets the value of PullRequestID.
func (s *ReassignReviewerReq) SetPullRequestID(val uuid.UUID) {
	s.PullRequestID = val
}

// SetOldUserID sets the value of OldUserID.
func (s *ReassignReviewerReq) SetOldUserID(val uuid.UUID) {
	s.OldUserID = val
}

type SetUserActiveBadRequest ErrorResponse

func (*SetUserActiveBadRequest) setUserActiveRes() {}

type SetUserActiveInternalServerError ErrorResponse

func (*SetUserActiveInternalServerError) setUserActiveRes() {}

type SetUserActiveNotFound ErrorResponse

func (*SetUserActiveNotFound) setUserActiveRes() {}

type SetUserActiveOK struct {
	User OptUser `json:"user"`
}

// GetUser returns the value of User.
func (s *SetUserActiveOK) GetUser() OptUser {
	return s.User
}

// SetUser sets the value of User.
func (s *SetUserActiveOK) SetUser(val OptUser) {
	s.User = val
}

func (*SetUserActiveOK) setUserActiveRes() {}

type SetUserActiveReq struct {
	UserID   uuid.UUID `json:"user_id"`
	IsActive bool      `json:"is_active"`
}

// GetUserID returns the value of UserID.
func (s *SetUserActiveReq) GetUserID() uuid.UUID {
	return s.UserID
}

// GetIsActive returns the value of IsActive.
func (s *SetUserActiveReq) GetIsActive() bool {
	return s.IsActive
}

// SetUserID sets the value of UserID.
func (s *SetUserActiveReq) SetUserID(val uuid.UUID) {
	s.UserID = val
}

// SetIsActive sets the value of IsActive.
func (s *SetUserActiveReq) SetIsActive(val bool) {
	s.IsActive = val
}

// Ref: #/components/schemas/Team
type Team struct {
	TeamName string       `json:"team_name"`
	Members  []TeamMember `json:"members"`
}

// GetTeamName returns the value of TeamName.
func (s *Team) GetTeamName() string {
	return s.TeamName
}

// GetMembers returns the value of Members.
func (s *Team) GetMembers() []TeamMember {
	return s.Members
}

// SetTeamName sets the value of TeamName.
func (s *Team) SetTeamName(val string) {
	s.TeamName = val
}

// SetMembers sets the value of Members.
func (s *Team) SetMembers(val []TeamMember) {
	s.Members = val
}

func (*Team) getTeamRes() {}

// Ref: #/components/schemas/TeamMember
type TeamMember struct {
	UserID   uuid.UUID `json:"user_id"`
	Username string    `json:"username"`
	IsActive bool      `json:"is_active"`
}

// GetUserID returns the value of UserID.
func (s *TeamMember) GetUserID() uuid.UUID {
	return s.UserID
}

// GetUsername returns the value of Username.
func (s *TeamMember) GetUsername() string {
	return s.Username
}

// GetIsActive returns the value of IsActive.
func (s *TeamMember) GetIsActive() bool {
	return s.IsActive
}

// SetUserID sets the value of UserID.
func (s *TeamMember) SetUserID(val uuid.UUID) {
	s.UserID = val
}

// SetUsername sets the value of Username.
func (s *TeamMember) SetUsername(val string) {
	s.Username = val
}

// SetIsActive sets the value of IsActive.
func (s *TeamMember) SetIsActive(val bool) {
	s.IsActive = val
}

// Ref: #/components/schemas/User
type User struct {
	UserID   uuid.UUID `json:"user_id"`
	Username string    `json:"username"`
	TeamName string    `json:"team_name"`
	IsActive bool      `json:"is_active"`
}

// GetUserID returns the value of UserID.
func (s *User) GetUserID() uuid.UUID {
	return s.UserID
}

// GetUsername returns the value of Username.
func (s *User) GetUsername() string {
	return s.Username
}

// GetTeamName returns the value of TeamName.
func (s *User) GetTeamName() string {
	return s.TeamName
}

// GetIsActive returns the value of IsActive.
func (s *User) GetIsActive() bool {
	return s.IsActive
}

// SetUserID sets the value of UserID.
func (s *User) SetUserID(val uuid.UUID) {
	s.UserID = val
}

// SetUsername sets the value of Username.
func (s *User) SetUsername(val string) {
	s.Username = val
}

// SetTeamName sets the value of TeamName.
func (s *User) SetTeamName(val string) {
	s.TeamName = val
}

// SetIsActive sets the value of IsActive.
func (s *User) SetIsActive(val bool) {
	s.IsActive = val
}
